
version: "3.9"
services:
  web:
    build: .
    container_name: ignited_django
    env_file: [.env]
    volumes: ["./:/app"]
    depends_on: [db]
    networks: [app_net]
  nginx:
    image: nginx:1.27-alpine
    container_name: ignited_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports: ["80:80"]
    depends_on: [web]
    networks: [app_net]
  db:
    image: postgres:16-alpine
    container_name: ignited_db
    env_file: [.env]
    volumes: ["db_data:/var/lib/postgresql/data"]
    networks: [app_net]
volumes: { db_data: {} }
networks: { app_net: { driver: bridge } }
